{% set name = "stow" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6fed67cf64deab6d3d9151a43e2c06c95cdfca6a88fab7d416f46a648b1d761d
  patches:
    - perllibdir.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - autoconf
    - automake
    - make
  host:
    - perl
    - perl-test-output
    - perl-io-stringy
  run:
    - perl

test:
  commands:
    - stow -h

about:
  home: https://www.gnu.org/software/stow/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: 'software package installation manager'
  description: >
    GNU Stow is a symlink farm manager which takes distinct packages of software and/or data located in separate directories on the filesystem, and makes them appear to be installed in the same place. For example, /usr/local/bin could contain symlinks to files within /usr/local/stow/emacs/bin, /usr/local/stow/perl/bin etc.,
    and likewise recursively for any other subdirectories such as .../share, .../man, and so on. This is particularly useful for keeping track of system-wide and per-user installations of software built from source, but can also facilitate a more controlled approach to management of configuration files in the user's home
    directory, especially when coupled with version control systems.
  doc_url: https://www.gnu.org/software/stow/manual/

extra:
  recipe-maintainers:
    - '0xaf1f'
